language: node_js
node_js:
  - "9"

env:
  - NODE_ENV=development

before_install:
  - npm i -g codecov

install:
  - npm install

script:
  - npm test:coverage
  - npm build
  - codecov

notifications:
  email: false